name: BRE

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  remote-execution:
    name: Bazel Remote Execution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: run nativelink
        run: |
          cargo install --git https://github.com/TraceMachina/nativelink --tag v0.2.0
          (nativelink bre/basic_cas.json &)

      - name: remote execution
        run: |
          bazel build --config=remote //bre/...
